# Generated by Django 2.2.28 on 2022-05-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=255, verbose_name='名前')),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='タイトル')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='サブタイトル')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='識別番号')),
                ('body', models.TextField(verbose_name='本文')),
                ('meta_description', models.CharField(blank=True, max_length=150, verbose_name='メタ情報')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='修正日時')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('published', models.BooleanField(default=False, verbose_name='公開日時')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='タグ')),
            ],
        ),
    ]
