version: '3'

services:
  # Vue(Frontend)
  frontend:
    container_name: Vue
    build:
      context: ./docker/vue
      dockerfile: Dockerfile
    networks:
     - django_net
    volumes:
     - ./src/frontend:/code
     - ./static:/static
     - ./template:/template
    expose:
     - "3000"
    tty: true
    depends_on:
     - backend

  # Django REST API
  backend:
    container_name: Django
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    networks:
      - django_net
    volumes:
      - ./src/backend:/code
      - ./static:/static
    expose:
      - "8001"
    tty: true
    depends_on:
      - db
 
  # My SQL Server
  db:
    container_name: MySQL
    image: mysql:latest
    networks:
      - django_net
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: blog_data
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - app.db.volume:/var/lib/mysql
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d

  # Nginx Settings
  nginx:
    container_name: Nginx
    image: nginx:1.17
    networks:
      - django_net
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/uwsgi_params:/etc/nginx/usgi_params
      - ./static:/static
      - ./src/frontend:/frontend
    depends_on:
      - backend
    
   
        
networks:
  django_net:
    driver: bridge

volumes:
  app.db.volume:
