# Generated by Django 2.2.28 on 2022-06-09 16:15

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220608_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profileBackground_directory_path, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profileThumbnail_directory_path, verbose_name='thumbnail'),
        ),
    ]
