# Generated by Django 2.2.28 on 2022-06-28 15:55

from django.db import migrations
import imagekit.models.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220610_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=user.models.profileBackground_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=user.models.profileThumbnail_directory_path),
        ),
    ]
